LexiconWebApp/Controllers/AjaxController.cs
using LexiconWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexiconWebApp.Controllers
{
    public class AjaxController : Controller
{
    public IActionResult Index()
    {
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            PeopleViewModel peopleViewModel = new PeopleViewModel() { PeopleListViewModel = createPersonViewModel.GetListPerson() };
            if (peopleViewModel.PeopleListViewModel.Count == 0)
                createPersonViewModel.MockPersonRepo();
            return View(peopleViewModel);     
    }

        [HttpGet]
        public IActionResult GetPerson()
        { 
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            
            List<Person> personList = createPersonViewModel.GetListPerson();
            return PartialView("_partialPeopleList", personList);   
        }


        [HttpPost]
        public IActionResult DeletePerson(int personId)
        {
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            Person person = createPersonViewModel.GetPersonById(personId);

            if (person != null)
            {
                if (createPersonViewModel.DeletePerson(person))
                    return StatusCode(200); //Status200OK	HTTP status code 200.
            }
            return StatusCode(400); // Status400BadRequest HTTP status code 400.
        }


        [HttpPost]
        public IActionResult FindPersonById(int personId)
        {
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            Person person = createPersonViewModel.GetPersonById(personId);
            List<Person> PersonList = new List<Person>();

            if (person != null) PersonList.Add(person);
            return PartialView("_partialPeopleList", PersonList);
        }
    }
}

LexiconWebApp/Controllers/DoctorController.cs
using LexiconWebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LexiconWebApp.Controllers
{
    public class DoctorController : Controller
    {
        [HttpGet("Doctor/FeverCheck")]
        public IActionResult FeverCheck()
        {
            return View();
        }
        
        [HttpPost("Doctor/FeverCheck")]
        public IActionResult FeverCheck(float temperature)
        {
            ViewBag.message = FeverCheckerModel.Fever(temperature);
            return View();
        }
    }
}

LexiconWebApp/Controllers/PeopleController.cs
using LexiconWebApp.Models;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Linq;

namespace LexiconMVC_Data.Controllers
{
    public class PeopleController : Controller
    {
        public IActionResult PeopleList()
        { 
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            PeopleViewModel peopleViewModel = new PeopleViewModel() { PeopleListViewModel = createPersonViewModel.GetListPerson() };
            if (peopleViewModel.PeopleListViewModel.Count == 0)
                createPersonViewModel.MockPersonRepo();

            return View(peopleViewModel);
        }

        public IActionResult DeletePerson(int id)
        {

            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            Person person = createPersonViewModel.GetPersonById(id);
            createPersonViewModel.DeletePerson(person);

            return RedirectToAction("PeopleList");
        }

        [HttpPost]
        public IActionResult PeopleList(PeopleViewModel peopleViewModel)
        {
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();
            peopleViewModel.PeopleListViewModel.Clear();

            foreach (Person person in createPersonViewModel.GetListPerson())  // search by name or city
            {
                if (person.Name.Contains(peopleViewModel.Filter, StringComparison.OrdinalIgnoreCase)||
                    person.City.Contains(peopleViewModel.Filter, StringComparison.OrdinalIgnoreCase))
                {
                    peopleViewModel.PeopleListViewModel.Add(person);
                }
            }
            return View(peopleViewModel);
        }


        [HttpPost]
        public IActionResult CreatePerson(CreatePersonViewModel addPersonViewModel)
        {
            PeopleViewModel peopleViewModel = new PeopleViewModel();
            CreatePersonViewModel createPersonViewModel = new CreatePersonViewModel();

            if (ModelState.IsValid)
            {
                peopleViewModel.Name = addPersonViewModel.Name;
                peopleViewModel.PhoneNumber = addPersonViewModel.PhoneNumber;
                peopleViewModel.City = addPersonViewModel.City;
                peopleViewModel.PeopleListViewModel = addPersonViewModel.GetListPerson();
                createPersonViewModel.CreatePerson(addPersonViewModel.Name, addPersonViewModel.PhoneNumber, addPersonViewModel.City);
                ViewBag.Message = "Person Added Successfully ";

                return View("PeopleList", peopleViewModel);
            }

            ViewBag.Message = "Error While Adding A Person" + ModelState.Values;
            return View("PeopleList", peopleViewModel);
        }

    }
}

LexiconWebApp/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <link rel="stylesheet" href="~/css/site.css">
    <meta charset="utf-8" />
    
    <title>@ViewBag.Title</title>
</head>
<body>
    <header>
        <nav>
            <div class="container">
                <ul>
                    <li>
                        <img src="~/img/Logo.png" alt="Page Logo" />
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Index"> Home</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="About"> About</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Contact"> Contact</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="Projects"> Projects</a>
                    </li>
                    <li>
                        <a asp-controller="Doctor" asp-action="FeverCheck"> Fever Check</a>
                    </li>
                    <li>
                        <a asp-controller="GuessingGame" asp-action="GuessingGame"> Guessing Game</a>
                    </li>

                    <li>
                        <a asp-controller="People" asp-action="PeopleList">People</a>
                    </li>

                    <li>
                        <a asp-controller="Ajax" asp-action="Index">People Ajax</a>
                    </li>

                </ul>
            </div>
        </nav>
    </header>
    <section>
        <div>
            @RenderBody()
        </div>
    </section>
    <footer>@DateTime.Now.ToShortDateString() &copy;Ahmad Zarour</footer>




    
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/js/PersonScript.js"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

LexiconWebApp/Views/Shared/_partialPeopleList.cshtml
@model List<Person>


<div class="container">
    <div class="row row-cols-md-5 justify-content-md-between">

        <div class="col-lg"><b> #</b></div>
        <div class="col-bold">
            <b>Name</b>
        </div>
        <div class="col-bold">
            <b>Phone Number</b>
        </div>
        <div class="col-bold">
            <b> City</b>
        </div>
        <div class="col-bold"><b>Action</b></div>
    </div>
</div>

<div class="row row-cols-md-5 justify-content-md-between" style="border:1px dashed black;">
    @{ foreach (Person person in Model)
        {

            <div class="col-md "> @person.Id </div>
            <div class="col-md"> @person.Name</div>
            <div class="col-md">@person.PhoneNumber</div>
            <div class="col-md"> @person.City</div>
            <div class="col-md">
                <a class="btn btn-danger btn-sm fw-bold float-start" onclick="location.href =
                    '@Url.Action("DeletePerson","People", new{ id= person.Id})'">Delete</a>
            </div>
        } }
</div>

LexiconWebApp/Views/Shared/_partialPersonList.cshtml
@model Person

<div class="row row-cols-md-5 justify-content-md-between" style="border:1px dashed black;">

            
            <div class="col-md "> @Model.Id </div>
            <div class="col-md"> @Model.Name</div>
            <div class="col-md">@Model.PhoneNumber</div>
            <div class="col-md"> @Model.City</div>
            <div class="col-md">
                <a class="btn btn-danger btn-sm fw-bold float-start" onclick="location.href =
                    '@Url.Action("DeletePerson","People", new{ id= @Model.Id})'">Delete</a>
            </div>
       
</div>